# New ports collection makefile for:	pkg-frenzy-sysutils
# Date created:		22 October 2005
# Whom:			technix@frenzy.org.ua
#
#

PORTNAME=	pkg-frenzy-sysutils
PORTVERSION=	1.1
CATEGORIES=	misc
MASTER_SITES=	# none
DISTFILES=	# none

MAINTAINER=	technix@frenzy.org.ua
COMMENT=	Frenzy LiveCD - sysutils

RUN_DEPENDS=	\
		adtool:${PORTSDIR}/sysutils/adtool \
		bashburn:${PORTSDIR}/sysutils/bashburn \
		bacula-fd:${PORTSDIR}/sysutils/bacula-client \
		ccze:${PORTSDIR}/sysutils/ccze \
		cdircmp:${PORTSDIR}/sysutils/cdircmp \
		mkisofs:${PORTSDIR}/sysutils/cdrtools \
		chgrep:${PORTSDIR}/sysutils/chgrep \
		clonehdd:${PORTSDIR}/sysutils/clonehdd \
		create_compressed_fs:${PORTSDIR}/sysutils/cloop-utils \
		cmdwatch:${PORTSDIR}/sysutils/cmdwatch \
		cmospwd:${PORTSDIR}/sysutils/cmospwd \
		colorize:${PORTSDIR}/sysutils/colorize \
		conky:${PORTSDIR}/sysutils/conky \
		chm:${PORTSDIR}/sysutils/consolehm \
		cpdup:${PORTSDIR}/sysutils/cpdup \
		burnP5:${PORTSDIR}/sysutils/cpuburn \
		crashme:${PORTSDIR}/sysutils/crashme \
		dcfldd:${PORTSDIR}/sysutils/dcfldd \
		dd_rescue:${PORTSDIR}/sysutils/dd_rescue \
		ddrescue:${PORTSDIR}/sysutils/ddrescue \
		detach:${PORTSDIR}/sysutils/detach \
		detox:${PORTSDIR}/sysutils/detox \
		di:${PORTSDIR}/sysutils/di \
		dmidecode:${PORTSDIR}/sysutils/dmidecode \
		dollyC:${PORTSDIR}/sysutils/dolly+ \
		dt:${PORTSDIR}/sysutils/dt \
		dump9660:${PORTSDIR}/sysutils/dump9660 \
		growisofs:${PORTSDIR}/sysutils/dvd+rw-tools \
		mkfs.ext2:${PORTSDIR}/sysutils/e2fsprogs \
		eject:${PORTSDIR}/sysutils/eject \
		evtViewer:${PORTSDIR}/sysutils/evtviewer \
		fatback:${PORTSDIR}/sysutils/fatback \
		ffs2recov:${PORTSDIR}/sysutils/ffs2recov \
		finfo:${PORTSDIR}/sysutils/finfo \
		foremost:${PORTSDIR}/sysutils/foremost \
		fpkg:${PORTSDIR}/sysutils/fpkg \
		curlftpfs:${PORTSDIR}/sysutils/fusefs-curlftpfs \
		ntfs-3g:${PORTSDIR}/sysutils/fusefs-ntfs \
		smbnetfs:${PORTSDIR}/sysutils/fusefs-smbnetfs \
		sshfs:${PORTSDIR}/sysutils/fusefs-sshfs \
		fuser:${PORTSDIR}/sysutils/fuser \
		ftrace:${PORTSDIR}/sysutils/ftrace \
		gpart:${PORTSDIR}/sysutils/gpart \
		gpkgdep:${PORTSDIR}/sysutils/gpkgdep \
		gpte:${PORTSDIR}/sysutils/gpte \
		grub:${PORTSDIR}/sysutils/grub \
		hammerhead:${PORTSDIR}/sysutils/hammerhead \
		iat:${PORTSDIR}/sysutils/iat \
		installwatch:${PORTSDIR}/sysutils/installwatch \
		isomaster:${PORTSDIR}/sysutils/isomaster \
		ipsc:${PORTSDIR}/sysutils/ipsc \
		lmmon:${PORTSDIR}/sysutils/lmmon \
		ldapvi:${PORTSDIR}/sysutils/ldapvi \
		log_analysis:${PORTSDIR}/sysutils/log_analysis \
		logmon:${PORTSDIR}/sysutils/logmon \
		logserial:${PORTSDIR}/sysutils/logserial \
		logtool:${PORTSDIR}/sysutils/logtool \
		lsof:${PORTSDIR}/sysutils/lsof \
		magicrescue:${PORTSDIR}/sysutils/magicrescue \
		makefs:${PORTSDIR}/sysutils/makefs \
		mapchan:${PORTSDIR}/sysutils/mapchan \
		mbmon:${PORTSDIR}/sysutils/mbmon \
		memdump:${PORTSDIR}/sysutils/memdump \
		memfetch:${PORTSDIR}/sysutils/memfetch \
		memgrep:${PORTSDIR}/sysutils/memgrep \
		memtest:${PORTSDIR}/sysutils/memtest \
		${LOCALBASE}/share/memtest86/floppy.bin:${PORTSDIR}/sysutils/memtest86 \
		mkfile:${PORTSDIR}/sysutils/mkfile \
		multitail:${PORTSDIR}/sysutils/multitail \
		muse:${PORTSDIR}/sysutils/muse \
		ntfsinfo:${PORTSDIR}/sysutils/ntfsprogs \
		lspci:${PORTSDIR}/sysutils/pciutils \
		pidof:${PORTSDIR}/sysutils/pidof \
		pipemeter:${PORTSDIR}/sysutils/pipemeter \
		phantom:${PORTSDIR}/sysutils/phantom \
		mkfs.reiserfs:${PORTSDIR}/sysutils/progsreiserfs \
		prips:${PORTSDIR}/sysutils/prips \
		pslist:${PORTSDIR}/sysutils/pslist \
		pstree:${PORTSDIR}/sysutils/pstree \
		pwd_unmkdb:${PORTSDIR}/sysutils/pwd_unmkdb \
		radeontool:${PORTSDIR}/sysutils/radeontool \
		recoverdm:${PORTSDIR}/sysutils/recoverdm \
		reed:${PORTSDIR}/sysutils/reed \
		rename:${PORTSDIR}/sysutils/rename \
		rfstool:${PORTSDIR}/sysutils/rfstool \
		scan_ffs:${PORTSDIR}/sysutils/scan_ffs \
		screen:${PORTSDIR}/sysutils/screen \
		screenie:${PORTSDIR}/sysutils/screenie \
		sdd:${PORTSDIR}/sysutils/sdd \
		searchmonkey:${PORTSDIR}/sysutils/searchmonkey \
		sfdisk:${PORTSDIR}/sysutils/sfdisk \
		sformat:${PORTSDIR}/sysutils/sformat \
		skill:${PORTSDIR}/sysutils/skill \
		ifind:${PORTSDIR}/sysutils/sleuthkit \
		sloth:${PORTSDIR}/sysutils/sloth \
		smartctl:${PORTSDIR}/sysutils/smartmontools \
		stress:${PORTSDIR}/sysutils/stress \
		tcplist:${PORTSDIR}/sysutils/tcplist \
		testdisk:${PORTSDIR}/sysutils/testdisk \
		udesc_dump:${PORTSDIR}/sysutils/udesc_dump \
		ufs_copy:${PORTSDIR}/sysutils/ufs_copy \
		vcp:${PORTSDIR}/sysutils/vcp \
		t2w:${PORTSDIR}/sysutils/wtmp-tools \
		x86info:${PORTSDIR}/sysutils/x86info \
		xmbmon:${PORTSDIR}/sysutils/xmbmon \
		xwlans:${PORTSDIR}/sysutils/xwlans \
		zeroer:${PORTSDIR}/sysutils/zeroer \
		zidrav:${PORTSDIR}/sysutils/zidrav \
		autopsy:${PORTSDIR}/sysutils/autopsy

#		diskprep:${PORTSDIR}/sysutils/diskprep \
#		abck:${PORTSDIR}/sysutils/abck \

.if defined (WITH_FRENZY_EXTENDED)
RUN_DEPENDS+=	\
		bbapm:${PORTSDIR}/sysutils/bbapm \
		cdf:${PORTSDIR}/sysutils/cdf \
		ghasher:${PORTSDIR}/sysutils/ghasher \
		graveman:${PORTSDIR}/sysutils/graveman \
		qtpkg:${PORTSDIR}/sysutils/qtpkg
.endif

#		mountsmb2:${PORTSDIR}/sysutils/mountsmb2 \

# ? maybe
# seatools

# removed
#		asapm:${PORTSDIR}/sysutils/asapm \
#		LinNeighborhood:${PORTSDIR}/sysutils/linneighborhood \
#unfetchable		installwatch:${PORTSDIR}/frenzy/installwatch \


# BROKEN IN 6.0
# fusefs-httpfs

PLIST_FILES=	bin/${PORTNAME}

NO_BUILD=	YES
NO_WRKSUBDIR=	YES


do-configure:
	@${CP} /etc/make.conf /etc/make.conf.${PORTNAME}
	@${CAT} ./pkg-conf >> /etc/make.conf

do-install:
	@${TOUCH} ${LOCALBASE}/bin/${PORTNAME}
	@${CHMOD} +x ${LOCALBASE}/bin/${PORTNAME}

post-install:
	@${CP} /etc/make.conf.${PORTNAME} /etc/make.conf
	@${RM} /etc/make.conf.${PORTNAME}

.include <bsd.port.mk>


# sysutils/autopsy
