#!/bin/sh
# PROVIDE: bootloader
# REQUIRE: installkernel
. ../config
. lib/lib.sh

if [ "$1" = "frenzy" -o "$1" = "all" ]; then
    stage_init
    stage_check
    cd boot
    ./make.sh
    cd ..
fi

stage_done
