#!/bin/sh
# PROVIDE: iso-mkuzip
# REQUIRE: iso-prepare
. ../config
. lib/lib.sh

if [ "$1" = "iso" -o "$1" = "all" ]; then
stage_init
stage_check

SORT="stages/iso/iso_sort"
FRENZY_TMP_ISO="${FRENZY_CD}/frenzy/frenzy.iso"
FRENZY_UZIP="${FRENZY_CD}/frenzy/frenzy.uzip"
FRENZY_KERNELD="${FRENZY_FS}/boot/kernel"

cd ..
# saving kernel
mv ${FRENZY_KERNELD}/kernel .
#
echo "[*] Creating temporary ISO. Please wait..."
mkisofs -lRNU -quiet -ldots -sort ${SORT} -o ${FRENZY_TMP_ISO} ${FRENZY_FS} > /dev/null 2>&1
echo "[*] Done."
echo "[*] Making compressed image. Please wait..."
mkuzip -o ${FRENZY_UZIP} -s ${BLOCKSIZE} ${FRENZY_TMP_ISO} > /dev/null 2>&1
echo "[*] Done."
rm -f ${FRENZY_TMP_ISO} > /dev/null 2>&1
# restoring kernel
mv kernel ${FRENZY_KERNELD}
#
stage_done

fi
