#!/bin/sh
# PROVIDE: iso-build
# REQUIRE: iso-mkuzip
. ../config
. lib/lib.sh

if [ "$1" = "iso" -o "$1" = "all" ]; then
stage_init
stage_check

cd ..
echo "[*] Creating Frenzy ISO."

# add version info
printf "${VERSION}" > ${FRENZY_CD}/boot/frenzy.version
makefs -t cd9660 -o "bootimage=i386;/boot/cdboot" -o rockridge -o no-emul-boot -o label=frenzy ${FRENZY_ISO}/${FRENZY_ISOIMAGE} ${FRENZY_CD}

echo "[*] Done."

fi

stage_done
