#!/bin/sh
# PROVIDE: kernel-build
# REQUIRE: world-build
. ../config
. lib/lib.sh

if [ "$1" = "build" -o "$1" = "all" ]; then
stage_init
stage_check

BASEDIR="${CURRDIR}/base"
SOURCEDIR="${CURRDIR}/../${SRCDIR}"
export __MAKE_CONF=${BASEDIR}/${MAKECONF}
export KERNCONFDIR=${BASEDIR}
export MAKEOBJDIRPREFIX="${CURRDIR}/../${FRENZY_BUILD}"

if [ ! -e ${BASEDIR}/$KERNCONFNAME ]; then
cd ${BASEDIR}/kernel
cat /dev/null > ${BASEDIR}/$KERNCONFNAME
cat * >> ${BASEDIR}/$KERNCONFNAME
cd ${CURRDIR}
fi

cd ${SOURCEDIR}
make -j3 buildkernel KERNCONF=${KERNCONFNAME}

stage_done

fi
