#!/bin/sh
# PROVIDE: packages-install-freebsd
# REQUIRE: packages-install-frenzy
. ../config
. lib/lib.sh

if [ "$1" = "frenzy" -o "$1" = "all" ]; then
stage_init
stage_check

echo "[*] Installing FreeBSD packages."

echo -n "["
cd ../${PKG_FREEBSD}

FAILEDPKG=""
for pkg in `ls |grep tbz$`
do
cat ${pkg} | chroot ${FRENZY_FS} pkg_add -f -
if [ $? -eq 1 ]; then
FAILEDPKG="${FAILEDPKG} ${pkg}"
echo "!${pkg}!"
fi
echo -n "."
done

# installing failed packages (they may require smth)
for pkg in `echo ${FAILEDPKG}`
do
cat ${pkg} | chroot ${FRENZY_FS} pkg_add -f -
echo -n ":"
done

echo "]"

rm -rf ${FRENZY_FS}/var/tmp/*
fi

stage_done

