#!/bin/sh
# PROVIDE: world-lite
# REQUIRE: bootloader
. ../config
. lib/lib.sh

if [ "$1" = "frenzy" -o "$1" = "all" ]; then
stage_init
stage_check

BASEDIR="${CURRDIR}/lite"

for i in `cat ${BASEDIR}/${RMFILE}` 
do
[ ! -d "${FRENZY_FS}/${i}" ] || rm -rf ${FRENZY_FS}/${i}
done
fi

stage_done
