#!/bin/sh
PROGRESS=".progress"
PARAM=$1

PARAMLS="build install frenzy iso all"

usage()
{
echo "${0} <targets>"
echo "where targets one of:"
echo "${PARAMLS}"
}


# Parameters: build install frenzy iso all
if [ $# -eq 0 ]; then
usage
exit
fi

STAGES=`realpath stages`

for EXEC in `cd ${STAGES} && rcorder -s nostart *`
do
cd ${STAGES}
/bin/sh ./$EXEC $PARAM
if [ $? -eq 1 ]; then
err 1 "Stage ${EXEC} incomplete"
fi
done