#!/bin/sh
# PROVIDE: iso-build
# REQUIRE: iso-mkuzip
. ../config
. lib/lib.sh

if [ "$1" = "iso" -o "$1" = "all" ]; then
stage_init
stage_check

cd ..
echo "[*] Creating Frenzy ISO."

# add version info
printf "${VERSION}" > ${FRENZY_CD}/boot/frenzy.version

mkisofs -quiet -b boot/cdboot -no-emul-boot -c boot/boot.catalog \
-boot-load-size 4 \
-r -J -D -V ${FRENZY_VOL} -o ${FRENZY_ISO}/${FRENZY_ISOIMAGE} ${FRENZY_CD}

echo "[*] Done."

stage_done

fi

