#!/bin/sh
# PROVIDE: world-build
# REQUIRE: FRENZY
. ../config
. lib/lib.sh

if [ "$1" = "build" -o "$1" = "all" ]; then
stage_init
stage_check

BASEDIR="${CURRDIR}/base"
SOURCEDIR="${CURRDIR}/../${SRCDIR}"
export __MAKE_CONF=${BASEDIR}/${MAKECONF}
export MAKEOBJDIRPREFIX="${CURRDIR}/../${FRENZY_BUILD}"

cd ${SOURCEDIR}
make buildworld ${MAKE_OPTIONS}

stage_done

fi