#!/bin/sh
# PROVIDE: world-lite
# REQUIRE: bootloader
. ../config
. lib/lib.sh

if [ "$1" = "frenzy" -o "$1" = "all" ]; then
stage_init
stage_check

BASEDIR="${CURRDIR}/lite"

for i in `cat ${BASEDIR}/${RMFILE}` 
do
rm -R ${CURRDIR}/../${FRENZY_FS}/${i} > /dev/null 2>&1
done

stage_done

fi